apiVersion: v1
kind: Service
metadata:
  name: demo-app-lb
  namespace: stage
  labels:
    app: demo-app
    environment: stage
spec:
  type: LoadBalancer
  selector:
    app: demo-app
    environment: stage
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
