apiVersion: v1
kind: Service
metadata:
  name: demo-app-lb
  namespace: prod
  labels:
    app: demo-app
    environment: prod
spec:
  type: LoadBalancer
  selector:
    app: demo-app
    environment: prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
